api_subdomain: api
admin_subdomain: admin
platform_subdomain: platform

ui_endpoint: http://api.zinger.pw

api_auth: lMkjDvjgc8r5dt2fY2gu13iX0kdjSXiBt6GfHihj
admin_auth: t1IIjV6ksT4yY9vIbQoMfmkHMoY5DiVEACCTM9au
platform_auth: qt1DLNGvnXJV72cggWmnklGVMK5DjcOGQFbB5OAG
google_client_id: 1045854179918-k05hppi6h6ghdpkkg7mjjk6g82ae2bbo.apps.googleusercontent.com
